#!/bin/sh

case "$1" in
    start)
        echo "Executing module_load and scull_load scripts"
        /usr/bin/module_load faulty
        /usr/bin/scull_load
        modprobe hello
        ;;
    stop)
        echo "Stopping module_load and scull_load scripts"
        /usr/bin/module_unload faulty
        /usr/bin/scull_unload
        rmmod hello
        ;;
      *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
